apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-backend
  template:
    metadata:
      labels:
        app: fashion-backend
    spec:
      containers:
      - name: backend
        image: sofiakulagina/fashion-backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-backend-service
spec:
  selector:
    app: fashion-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-nginx
  template:
    metadata:
      labels:
        app: fashion-nginx
    spec:
      containers:
      - name: nginx
        image: sofiakulagina/fashion-nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-nginx-service
spec:
  selector:
    app: fashion-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
