---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-app
  template:
    metadata:
      labels:
        app: fashion-app
    spec:
      containers:
      - name: fashion-app-container
        image: s1mphonia/fashion-guide:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-app-service
spec:
  selector:
    app: fashion-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
