name: Fashion Guide CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build backend image
      run: docker build -t s1mphonia/fashion-backend:latest ./backend

    - name: Build frontend image
      run: docker build -t s1mphonia/fashion-nginx:latest ./frontend

    - name: Run backend container
      run: docker run -d -p 8000:8000 --name test-backend s1mphonia/fashion-backend:latest

    - name: Wait for backend
      run: sleep 5

    - name: Test backend API root
      run: |
        curl --fail http://localhost:8000/ | grep "Fashion Trends Guide API" && echo "✅ Backend OK" || (echo "❌ Backend FAIL" && exit 1)

    - name: Run frontend container
      run: docker run -d -p 8080:80 --name test-frontend s1mphonia/fashion-nginx:latest

    - name: Wait for frontend
      run: sleep 5

    - name: Test frontend page
      run: |
        curl -s http://localhost:8080 | grep "Fashion Survival Guide" && echo "✅ Frontend OK" || (echo "❌ Frontend FAIL" && exit 1)

    - name: Push backend image
      run: docker push s1mphonia/fashion-backend:latest

    - name: Push frontend image
      run: docker push s1mphonia/fashion-nginx:latest
